version: '3.8'

services:
  backend:
    build:
      context: ./supchat-backend
    container_name: supchat-backend
    ports:
      - "3000:3000"
    env_file:
      - ./supchat-backend/.env           # Charge toutes vos vars d’env depuis .env
    depends_on:
      - mongodb
    volumes:
      - ./supchat-backend/uploads:/app/uploads
    restart: always

  frontend:
    build:
      context: ./supchat-frontend
    container_name: supchat-frontend
    ports:
      - "3001:80"
    depends_on:
      - backend
    # Pas besoin d’autres vars si tout est bundlé à la build

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
