#version: '3.8'

services:
  backend:
    build:
      context: ./supchat-backend
    container_name: supchat-backend
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb+srv://adminsupchat:QKnX2fNJMDFW23P4@supchat-cluster.ddto3.mongodb.net/?retryWrites=true&w=majority&appName=supchat-cluster
    depends_on:
      - mongodb
    volumes:
      - "./supchat-backend/uploads:/app/uploads"
    restart: always

  frontend:
    build:
      context: ./supchat-frontend
    container_name: supchat-frontend
    ports:
      - "3001:80"
    depends_on:
      - backend
    # Pas forcément besoin d'environnement pour le front,
    # sauf si tu veux passer des variables à build.

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:

  # Commande Docker pour lancer le server "docker-compose up --build"
  # Commande Docker pour stopper le server, dans un autre CMD "docker-compose down"