version: '3.8'

services:
  backend:
    build:
      context: ./supchat-backend
    ports:
      - "3000:3000"
    volumes:
      - /node_modules
    environment:
      - MONGO_URI=mongodb+srv://adminsupchat:QKnX2fNJMDFW23P4@supchat-cluster.ddto3.mongodb.net/?retryWrites=true&w=majority&appName=supchat-cluster
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:

    # Comande Docker "docker-compose up --build"